%%Returns the loss function used by the model.  
function [params] = getModelParams() 
    params = trainingOptions('adam', ...
    'MaxEpochs',300, ...         
    'MiniBatchSize',128, ...   
    'Shuffle','every-epoch', ...
    'InitialLearnRate',1e-3, ...
    'Plots','training-progress', ...
    'Verbose',true);